//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoNeke.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoNeke.Ressources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 1.
        /// </summary>
        internal static string Address_AddressLine {
            get {
                return ResourceManager.GetString("Address_AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 2.
        /// </summary>
        internal static string Address_AddressLine2 {
            get {
                return ResourceManager.GetString("Address_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        internal static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        internal static string Address_TypeStreet {
            get {
                return ResourceManager.GetString("Address_TypeStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrateur.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;adhesion.
        /// </summary>
        internal static string Assurance_DateSuscription {
            get {
                return ResourceManager.GetString("Assurance_DateSuscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie Assurance.
        /// </summary>
        internal static string Assurance_NomAssurance {
            get {
                return ResourceManager.GetString("Assurance_NomAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        internal static string City_Country {
            get {
                return ResourceManager.GetString("City_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        internal static string City_Departement {
            get {
                return ResourceManager.GetString("City_Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        internal static string City_DepartementPK {
            get {
                return ResourceManager.GetString("City_DepartementPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région.
        /// </summary>
        internal static string City_Region {
            get {
                return ResourceManager.GetString("City_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        internal static string City_ZipCode {
            get {
                return ResourceManager.GetString("City_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        internal static string Civility_Gender {
            get {
                return ResourceManager.GetString("Civility_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mme.
        /// </summary>
        internal static string CivilityEnum_Miss {
            get {
                return ResourceManager.GetString("CivilityEnum_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mlle.
        /// </summary>
        internal static string CivilityEnum_Misses {
            get {
                return ResourceManager.GetString("CivilityEnum_Misses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string CivilityEnum_Mister {
            get {
                return ResourceManager.GetString("CivilityEnum_Mister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro Kbis.
        /// </summary>
        internal static string Commune_CodeInsee {
            get {
                return ResourceManager.GetString("Commune_CodeInsee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant Balise.
        /// </summary>
        internal static string DevicePosition_DeviceId {
            get {
                return ResourceManager.GetString("DevicePosition_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string DevicePosition_Latitude {
            get {
                return ResourceManager.GetString("DevicePosition_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string DevicePosition_Longitude {
            get {
                return ResourceManager.GetString("DevicePosition_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        internal static string DevicePosition_Number {
            get {
                return ResourceManager.GetString("DevicePosition_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date et Heure.
        /// </summary>
        internal static string DevicePosition_Time {
            get {
                return ResourceManager.GetString("DevicePosition_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien.
        /// </summary>
        internal static string DevicePosition_Url {
            get {
                return ResourceManager.GetString("DevicePosition_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        internal static string Entreprise_EntrepriseName {
            get {
                return ResourceManager.GetString("Entreprise_EntrepriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren.
        /// </summary>
        internal static string Entreprise_SirenSiret {
            get {
                return ResourceManager.GetString("Entreprise_SirenSiret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrique.
        /// </summary>
        internal static string Gaz_Electric {
            get {
                return ResourceManager.GetString("Gaz_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoil.
        /// </summary>
        internal static string Gaz_Gazoil {
            get {
                return ResourceManager.GetString("Gaz_Gazoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPL.
        /// </summary>
        internal static string Gaz_GPL {
            get {
                return ResourceManager.GetString("Gaz_GPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybride.
        /// </summary>
        internal static string Gaz_Hybrid {
            get {
                return ResourceManager.GetString("Gaz_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans Plomb.
        /// </summary>
        internal static string Gaz_Unleaded {
            get {
                return ResourceManager.GetString("Gaz_Unleaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femme.
        /// </summary>
        internal static string GenderEnum_Female {
            get {
                return ResourceManager.GetString("GenderEnum_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homme.
        /// </summary>
        internal static string GenderEnum_Male {
            get {
                return ResourceManager.GetString("GenderEnum_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite Adresse.
        /// </summary>
        internal static string Person_Address2 {
            get {
                return ResourceManager.GetString("Person_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilité.
        /// </summary>
        internal static string Person_Civility {
            get {
                return ResourceManager.GetString("Person_Civility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        internal static string Person_DateOfBirth {
            get {
                return ResourceManager.GetString("Person_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string Person_FirstName {
            get {
                return ResourceManager.GetString("Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Person_LastName {
            get {
                return ResourceManager.GetString("Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationnalité.
        /// </summary>
        internal static string Person_Nationality {
            get {
                return ResourceManager.GetString("Person_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste.
        /// </summary>
        internal static string Person_Roles {
            get {
                return ResourceManager.GetString("Person_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        internal static string PersonHasVehicle_EndDate {
            get {
                return ResourceManager.GetString("PersonHasVehicle_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identité.
        /// </summary>
        internal static string PersonHasVehicle_Person {
            get {
                return ResourceManager.GetString("PersonHasVehicle_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        internal static string PersonHasVehicle_StartDate {
            get {
                return ResourceManager.GetString("PersonHasVehicle_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voiture.
        /// </summary>
        internal static string PersonHasVehicle_Vehicle {
            get {
                return ResourceManager.GetString("PersonHasVehicle_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string SideEnum_Center {
            get {
                return ResourceManager.GetString("SideEnum_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est.
        /// </summary>
        internal static string SideEnum_East {
            get {
                return ResourceManager.GetString("SideEnum_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord.
        /// </summary>
        internal static string SideEnum_North {
            get {
                return ResourceManager.GetString("SideEnum_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sud.
        /// </summary>
        internal static string SideEnum_South {
            get {
                return ResourceManager.GetString("SideEnum_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouest.
        /// </summary>
        internal static string SideEnum_West {
            get {
                return ResourceManager.GetString("SideEnum_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allée.
        /// </summary>
        internal static string TypeCommandEnum_Allee {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Allee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenue.
        /// </summary>
        internal static string TypeCommandEnum_Avenue {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Avenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boulevard.
        /// </summary>
        internal static string TypeCommandEnum_Boulevar {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Boulevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise en écoute.
        /// </summary>
        internal static string TypeCommandEnum_Comunicate {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Comunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        internal static string TypeCommandEnum_History {
            get {
                return ResourceManager.GetString("TypeCommandEnum_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Géolocaliser.
        /// </summary>
        internal static string TypeCommandEnum_Locate {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string TypeCommandEnum_Place {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartier.
        /// </summary>
        internal static string TypeCommandEnum_Quartier {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Quartier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string TypeCommandEnum_Route {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        internal static string TypeCommandEnum_Rue {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper le moteur.
        /// </summary>
        internal static string TypeCommandEnum_ShutdownEngine {
            get {
                return ResourceManager.GetString("TypeCommandEnum_ShutdownEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro Mobile.
        /// </summary>
        internal static string User_CellPhoneNumber {
            get {
                return ResourceManager.GetString("User_CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilité.
        /// </summary>
        internal static string User_Civility {
            get {
                return ResourceManager.GetString("User_Civility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        internal static string User_Entreprise {
            get {
                return ResourceManager.GetString("User_Entreprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro Fixe.
        /// </summary>
        internal static string User_HousePhoneNumber {
            get {
                return ResourceManager.GetString("User_HousePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string User_Roles {
            get {
                return ResourceManager.GetString("User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro professionel.
        /// </summary>
        internal static string User_WorkPhoneNumber {
            get {
                return ResourceManager.GetString("User_WorkPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque.
        /// </summary>
        internal static string VehicleMake_Make {
            get {
                return ResourceManager.GetString("VehicleMake_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modéle.
        /// </summary>
        internal static string VehicleModel_Model {
            get {
                return ResourceManager.GetString("VehicleModel_Model", resourceCulture);
            }
        }
    }
}
