//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoNeke.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoNeke.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adrésse 1.
        /// </summary>
        internal static string Address_AddressLine {
            get {
                return ResourceManager.GetString("Address_AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adrésse 2.
        /// </summary>
        internal static string Address_AddressLine2 {
            get {
                return ResourceManager.GetString("Address_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        internal static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rue.
        /// </summary>
        internal static string Address_TypeStreet {
            get {
                return ResourceManager.GetString("Address_TypeStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;adhesion.
        /// </summary>
        internal static string Assurance_DateSuscription {
            get {
                return ResourceManager.GetString("Assurance_DateSuscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compagnie Assurance.
        /// </summary>
        internal static string Assurance_NomAssurance {
            get {
                return ResourceManager.GetString("Assurance_NomAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        internal static string City_Country {
            get {
                return ResourceManager.GetString("City_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        internal static string City_Departement {
            get {
                return ResourceManager.GetString("City_Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        internal static string City_DepartementPK {
            get {
                return ResourceManager.GetString("City_DepartementPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Région.
        /// </summary>
        internal static string City_Region {
            get {
                return ResourceManager.GetString("City_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Postal.
        /// </summary>
        internal static string City_ZipCode {
            get {
                return ResourceManager.GetString("City_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe.
        /// </summary>
        internal static string Civility_Gender {
            get {
                return ResourceManager.GetString("Civility_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mme.
        /// </summary>
        internal static string CivilityEnum_Miss {
            get {
                return ResourceManager.GetString("CivilityEnum_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mlle.
        /// </summary>
        internal static string CivilityEnum_Misses {
            get {
                return ResourceManager.GetString("CivilityEnum_Misses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mr.
        /// </summary>
        internal static string CivilityEnum_Mister {
            get {
                return ResourceManager.GetString("CivilityEnum_Mister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro Kbis.
        /// </summary>
        internal static string Commune_CodeInsee {
            get {
                return ResourceManager.GetString("Commune_CodeInsee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant Balise.
        /// </summary>
        internal static string DevicePosition_DeviceId {
            get {
                return ResourceManager.GetString("DevicePosition_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latitude.
        /// </summary>
        internal static string DevicePosition_Latitude {
            get {
                return ResourceManager.GetString("DevicePosition_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longitude.
        /// </summary>
        internal static string DevicePosition_Longitude {
            get {
                return ResourceManager.GetString("DevicePosition_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        internal static string DevicePosition_Number {
            get {
                return ResourceManager.GetString("DevicePosition_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date et Heure.
        /// </summary>
        internal static string DevicePosition_Time {
            get {
                return ResourceManager.GetString("DevicePosition_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien.
        /// </summary>
        internal static string DevicePosition_Url {
            get {
                return ResourceManager.GetString("DevicePosition_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Société.
        /// </summary>
        internal static string Entreprise_EntrepriseName {
            get {
                return ResourceManager.GetString("Entreprise_EntrepriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Siren.
        /// </summary>
        internal static string Entreprise_SirenSiret {
            get {
                return ResourceManager.GetString("Entreprise_SirenSiret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electrique.
        /// </summary>
        internal static string Gaz_Electric {
            get {
                return ResourceManager.GetString("Gaz_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gasoil.
        /// </summary>
        internal static string Gaz_Gazoil {
            get {
                return ResourceManager.GetString("Gaz_Gazoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GPL.
        /// </summary>
        internal static string Gaz_GPL {
            get {
                return ResourceManager.GetString("Gaz_GPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hybride.
        /// </summary>
        internal static string Gaz_Hybrid {
            get {
                return ResourceManager.GetString("Gaz_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sans Plomb.
        /// </summary>
        internal static string Gaz_Unleaded {
            get {
                return ResourceManager.GetString("Gaz_Unleaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Femme.
        /// </summary>
        internal static string GenderEnum_Female {
            get {
                return ResourceManager.GetString("GenderEnum_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Homme.
        /// </summary>
        internal static string GenderEnum_Male {
            get {
                return ResourceManager.GetString("GenderEnum_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suite Adresse.
        /// </summary>
        internal static string Person_Address2 {
            get {
                return ResourceManager.GetString("Person_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Civilité.
        /// </summary>
        internal static string Person_Civility {
            get {
                return ResourceManager.GetString("Person_Civility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance.
        /// </summary>
        internal static string Person_DateOfBirth {
            get {
                return ResourceManager.GetString("Person_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string Person_FirstName {
            get {
                return ResourceManager.GetString("Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string Person_LastName {
            get {
                return ResourceManager.GetString("Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationnalité.
        /// </summary>
        internal static string Person_Nationality {
            get {
                return ResourceManager.GetString("Person_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poste.
        /// </summary>
        internal static string Person_Roles {
            get {
                return ResourceManager.GetString("Person_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin.
        /// </summary>
        internal static string PersonHasVehicle_EndDate {
            get {
                return ResourceManager.GetString("PersonHasVehicle_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identité.
        /// </summary>
        internal static string PersonHasVehicle_Person {
            get {
                return ResourceManager.GetString("PersonHasVehicle_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de début.
        /// </summary>
        internal static string PersonHasVehicle_StartDate {
            get {
                return ResourceManager.GetString("PersonHasVehicle_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voiture.
        /// </summary>
        internal static string PersonHasVehicle_Vehicle {
            get {
                return ResourceManager.GetString("PersonHasVehicle_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre.
        /// </summary>
        internal static string SideEnum_Center {
            get {
                return ResourceManager.GetString("SideEnum_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Est.
        /// </summary>
        internal static string SideEnum_East {
            get {
                return ResourceManager.GetString("SideEnum_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nord.
        /// </summary>
        internal static string SideEnum_North {
            get {
                return ResourceManager.GetString("SideEnum_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sud.
        /// </summary>
        internal static string SideEnum_South {
            get {
                return ResourceManager.GetString("SideEnum_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouest.
        /// </summary>
        internal static string SideEnum_West {
            get {
                return ResourceManager.GetString("SideEnum_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allée.
        /// </summary>
        internal static string TypeCommandEnum_Allee {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Allee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avenue.
        /// </summary>
        internal static string TypeCommandEnum_Avenue {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Avenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boulevard.
        /// </summary>
        internal static string TypeCommandEnum_Boulevar {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Boulevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise en écoute.
        /// </summary>
        internal static string TypeCommandEnum_Comunicate {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Comunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        internal static string TypeCommandEnum_History {
            get {
                return ResourceManager.GetString("TypeCommandEnum_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Géolocaliser.
        /// </summary>
        internal static string TypeCommandEnum_Locate {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Place.
        /// </summary>
        internal static string TypeCommandEnum_Place {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quartier.
        /// </summary>
        internal static string TypeCommandEnum_Quartier {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Quartier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Route.
        /// </summary>
        internal static string TypeCommandEnum_Route {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rue.
        /// </summary>
        internal static string TypeCommandEnum_Rue {
            get {
                return ResourceManager.GetString("TypeCommandEnum_Rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couper le moteur.
        /// </summary>
        internal static string TypeCommandEnum_ShutdownEngine {
            get {
                return ResourceManager.GetString("TypeCommandEnum_ShutdownEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marque.
        /// </summary>
        internal static string VehicleMake_Make {
            get {
                return ResourceManager.GetString("VehicleMake_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modéle.
        /// </summary>
        internal static string VehicleModel_Model {
            get {
                return ResourceManager.GetString("VehicleModel_Model", resourceCulture);
            }
        }
    }
}
